# CONFIGURAZIONE GENERALE
title: Archivio Appunti Universitari
description: Lezioni di Ingegneria Informatica, Fondamenti di Programmazione e Analisi 1.
baseurl: /Fondamenti_di_Programmazione

# IMPOSTAZIONI DEL TEMA
remote_theme: just-the-docs/just-the-docs

# CONFIGURAZIONE DELLA BARRA LATERALE
# Qui useremo le "Collezioni" per raggruppare le materie
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/andnic04/Fondamenti_di_Programmazione